[workspace]
authors = ["Taeyoon Kim <deepthought@postech.ac.kr>"]
channels = ["conda-forge"]
name = "pharma-hands-on-exercises"
platforms = ["osx-arm64", "linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
quarto = ">=1.7.32,<2"
r-tidyverse = ">=2.0.0,<3"
r-rio = ">=1.2.3,<2"
r-haven = ">=2.5.4,<3"
r-skimr = ">=2.1.5,<3"
r-htmltable = ">=2.4.3,<3"
r-rlang = ">=1.1.6,<2"
r-ggdist = ">=3.3.0,<4"
r-cowplot = ">=1.2.0,<2"
r-testthat = ">=3.2.3,<4"
r-gt = ">=1.0.0,<2"
r-readr = ">=2.1.5,<3"
r-usethis = ">=3.1.0,<4"
r-knitr = ">=1.50,<2"
r-tinytex = ">=0.57,<0.58"
r-rmarkdown = ">=2.29,<3"
r-glue = ">=1.8.0,<2"
r-gghighlight = ">=0.5.0,<0.6"
r-ggridges = ">=0.5.6,<0.6"
r-patchwork = ">=1.3.1,<2"
r-reprex = ">=2.1.1,<3"
r-dplyr = ">=1.1.4,<2"
r-sessioninfo = ">=1.2.3,<2"
