project:
  type: book

book:
  title: "Pharma Hands-on Exercises"
  author:
    - Mike K Smith
    - Natalia Andriychuk
    - Samir Parmar
    - Leanne Vicente
    - Rajni Bhaya
    - Taeyoon Kim
  date: "2025-07-08"
  chapters:
    - index.qmd
    - MiniProject1_ko.qmd
    - MiniProject2_ko.qmd
    - MiniProject3_ko.qmd
    - MiniProject4_ko.qmd
    - MiniProject5_ko.qmd
    - MiniProject6_ko.qmd
    - MiniProject7_ko.qmd
    - MiniProject8_ko.qmd 
    - MiniProject9_ko.qmd
    - MiniProject10_ko.qmd
    - MiniProject11_ko.qmd
    - MiniProject12_ko.qmd
    - MiniProject13_ko.qmd
    - MiniProject14_ko.qmd

#bibliography: references.bib
link-citations: true

format:
  html:
    theme:
      - cosmo
      - brand
  pdf:
    documentclass: report
    papersize: a4
    geometry:
      - top=25mm
      - left=25mm
      - right=25mm
      - bottom=25mm
    toc: true
    toc-depth: 2
    number-sections: true
    colorlinks: true
    fig_width: 3
    fig_height: 2
    fig_caption: true
    df_print: kable
    highlight: tango
    include-in-header: 
      text: |
        \usepackage{pdfpages}
        \usepackage{fvextra}
        \DefineVerbatimEnvironment{Highlighting}{Verbatim}{
          commandchars=\\\{\},
          breaklines, breaknonspaceingroup, breakanywhere
        }

mainfont: "Noto Serif CJK KR"
sansfont: "Noto Sans CJK KR"
